title: Aotearoa Youth Figures
subtitle: Explore data for and about young people in Aotearoa
description: A site with open data, tools, and resources for young people in Aotearoa.
analytics: true
# analytics is a boolean value that determinees whether the woopra file is enabled.

# collections are groups of pages/posts that can be displayed in blocks on the homepage and the sidebar menu.
collections:
  topics:
    output: true

markdown: kramdown

sass:
    style: compressed

include:
  - .htaccess
  - assets/css/main.scss

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md